import common

fields = [
    # 00 00 10
    common.Field(
        name="Heating_Status_Setting",
        direction=0x00,
        address=0x00,
        packet_type=0x10,
        position=0,
        n_bytes=1,
        bitmask=0x1,
        data_type=common.flag,
    ),
    common.Field(
        name="DHW_Status_Setting",
        direction=0x00,
        address=0x00,
        packet_type=0x10,
        position=2,
        n_bytes=1,
        bitmask=0x1,
        data_type=common.flag,
    ),
    common.Field(
        # Unknown byte that continously jumps between values in the first and the second byte
        name="Unknown byte",
        direction=0x00,
        address=0x00,
        packet_type=0x10,
        position=3,
        n_bytes=2,
        data_type=common.ignore,
    ),
    common.Field(
        # This might also be an uint8 with a single byte
        name="DHW_Setpoint",
        direction=0x00,
        address=0x00,
        packet_type=0x10,
        position=7,
        n_bytes=2,
        data_type=common.f8s8,
    ),
    common.Field(
        name="Silent_Setting",
        direction=0x00,
        address=0x00,
        packet_type=0x10,
        position=9,
        n_bytes=1,
        bitmask=0x1,
        data_type=common.flag,
    ),
    # 00 00 11
    common.Field(
        name="Unknown byte 00 00 11 1",
        direction=0x00,
        address=0x00,
        packet_type=0x11,
        position=1,
        n_bytes=1,
        data_type=common.ignore,
    ),
    common.Field(
        # Alternates between values like AC, C4, 96, 7E
        name="Unknown byte 00 00 11 2",
        direction=0x00,
        address=0x00,
        packet_type=0x11,
        position=2,
        n_bytes=1,
        data_type=common.ignore,
    ),
    # 00 00 12: seems to contain time but not the time on the display
    common.Field(
        # Mo 0 -> 6
        name="Time_dow",
        direction=0x00,
        address=0x00,
        packet_type=0x12,
        position=1,
        n_bytes=1,
        data_type=common.u8,
    ),
    common.Field(
        name="Time_hours",
        direction=0x00,
        address=0x00,
        packet_type=0x12,
        position=2,
        n_bytes=1,
        data_type=common.u8,
    ),
    common.Field(
        name="Time_minutes",
        direction=0x00,
        address=0x00,
        packet_type=0x12,
        position=3,
        n_bytes=1,
        data_type=common.u8,
    ),
    common.Field(
        name="Time_seconds",
        direction=0x00,
        address=0x00,
        packet_type=0x12,
        position=4,
        n_bytes=1,
        data_type=common.u8,
    ),
    # 00 00 0D
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=1,
        n_bytes=1,
        data_type=common.ignore,
    ),
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=3,
        n_bytes=1,
        data_type=common.ignore,
    ),
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=5,
        n_bytes=1,
        data_type=common.ignore,
    ),
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=6,
        n_bytes=2,
        data_type=common.ignore,
    ),
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=8,
        n_bytes=2,
        data_type=common.ignore,
    ),
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=11,
        n_bytes=1,
        data_type=common.ignore,
    ),
    common.Field(
        name="Unknown field",
        direction=0x00,
        address=0x00,
        packet_type=0x0D,
        position=14,
        n_bytes=2,
        data_type=common.ignore,
    ),
    # 00 00 0E
    common.Field(
        name="Unknown counter",
        direction=0x00,
        address=0x00,
        packet_type=0x0E,
        position=2,
        n_bytes=2,
        data_type=common.ignore,
    ),

    # 40 00 10
    common.Field(
        name="Heating_Status",
        direction=0x40,
        address=0x00,
        packet_type=0x10,
        position=0,
        n_bytes=1,
        bitmask=0x1,
        data_type=common.flag,
    ),
    common.Field(
        name="DHW_Status",
        direction=0x40,
        address=0x00,
        packet_type=0x10,
        position=3,
        n_bytes=1,
        bitmask=0x1,
        data_type=common.flag,
    ),
    common.Field(
        name="Target_Temperature_Leaving_Water",
        direction=0x40,
        address=0x00,
        packet_type=0x10,
        position=4,
        n_bytes=2,
        data_type=common.f8s8,
    ),
    common.Field(
        name="Temperature_outside",
        direction=0x40,
        address=0x00,
        packet_type=0x10,
        position=14,
        n_bytes=2,
        data_type=common.f8_8r,
    ),
    # 40 00 11
    common.Field(
        name="Unknown field",
        direction=0x40,
        address=0x00,
        packet_type=0x11,
        position=0,
        n_bytes=2,
        data_type=common.f8_8r,
    ),
    common.Field(
        name="Temperature_DHW_Tank",
        direction=0x40,
        address=0x00,
        packet_type=0x11,
        position=2,
        n_bytes=2,
        data_type=common.f8_8r,
    ),
    common.Field(
        name="Temperature_HP2Gas_Water",
        direction=0x40,
        address=0x00,
        packet_type=0x11,
        position=4,
        n_bytes=2,
        data_type=common.f8_8r,
    ),
    common.Field(
        name="Temperature_Return_Water",
        direction=0x40,
        address=0x00,
        packet_type=0x11,
        position=6,
        n_bytes=2,
        data_type=common.f8_8r,
    ),
    common.Field(
        name="Temperature_Leaving_Water",
        direction=0x40,
        address=0x00,
        packet_type=0x11,
        position=8,
        n_bytes=2,
        data_type=common.f8_8r,
    ),
    common.Field(
        name="Temperature_Refrigerant_1",
        direction=0x40,
        address=0x00,
        packet_type=0x11,
        position=10,
        n_bytes=2,
        data_type=common.f8_8r,
    ),

    # 40 00 0D
    common.Field(
        # At least a 24 bit counter. Currently the first leading 00 byte assumed to be part of it as well
        name="Unknown counter",
        direction=0x40,
        address=0x00,
        packet_type=0x0D,
        position=3,
        n_bytes=4,
        data_type=common.ignore,
    ),

    common.Field(
        # value that changes without changing settings
        name="Unknown byte",
        direction=0x40,
        address=0x00,
        packet_type=0x0D,
        position=9,
        n_bytes=1,
        data_type=common.ignore,
    ),

    # 40 00 0E
    common.Field(
        # At least a 16 bit counter
        name="Unknown counter",
        direction=0x40,
        address=0x00,
        packet_type=0x0E,
        position=2,
        n_bytes=2,
        data_type=common.ignore,
    ),

    # 40 00 0F
    common.Field(
        # value that changes without changing settings
        name="Unknown 2 bytes",
        direction=0x40,
        address=0x00,
        packet_type=0x0F,
        position=2,
        n_bytes=2,
        data_type=common.ignore,
    ),

    # fields to ignore to improve detection of changes during reverse engineering
    common.Field(
        name="ignore",
        direction=0x00,
        address=0x01,
        packet_type=0x20,
        position=0,
        n_bytes=0,
        data_type=common.ignore,
    ),
    common.Field(
        name="ignore",
        direction=0x80,
        address=0x80,
        packet_type=0x00,
        position=0,
        n_bytes=0,
        data_type=common.ignore,
    ),
    # fields to inspect closer

]
